---

- name: copy config files 
  copy: >
    src=policy dest=/etc/shorewall/policy owner=root group=root mode=0644

- name: config interfaces
  template: >
    src=interfaces.j2
    dest=/etc/shorewall/interfaces
  notify:
    - shorewall restart
  sudo: yes

- name: config rules
  template: >
    src=rules.j2
    dest=/etc/shorewall/rules
  notify:
    - shorewall restart
  sudo: yes

- name: config zones
  template: >
    src=zones.j2
    dest=/etc/shorewall/zones
  notify:
    - shorewall restart
  sudo: yes